{% set name = "meshio" %}
{% set version = "2.3.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f2e3a6017d79273b3f5815273584970f32a97eb71035ba2a26d30a27325b6467

build:
  noarch: python
  number: 0
  entry_points:
    - meshio-convert = meshio.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python <3
    - pip
    - setuptools
  run:
    - python <3
    - numpy
    - netCDF4
    - h5py
    - lxml

test:
  imports:
    - meshio
  commands:
    - meshio-convert --help

about:
  home: "https://github.com/nschloe/meshio"
  license: MIT
  license_family: MIT
  summary: "I/O for various mesh formats"

extra:
  recipe-maintainers:
    - nschloe
    - MuellerSeb
