{% set name = "meshio" %}
{% set version = "5.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5676f63e0d993fc91a318f78571ea179e2aa4f79098e631bd8b0ec3764e8e94a

build:
  noarch: python
  number: 0
  entry_points:
    - meshio = meshio._cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3.7
    - importlib_metadata
    - numpy
    - netCDF4
    - rich
    - h5py

test:
  requires:
    - pytest
    - netCDF4
    - h5py
  source_files:
    - README.md
    - tests
  imports:
    - meshio
  commands:
    - meshio --help
    - python -m pytest

about:
  home: https://github.com/nschloe/meshio
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: I/O for various mesh formats

extra:
  recipe-maintainers:
    - nschloe
    - MuellerSeb
    - banesullivan
