{% set name = "meshio" %}
{% set version = "4.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 299e634df13ecbd71f1e9c601592705af3a884c5817490a7580f37e9665e3f2f

build:
  noarch: python
  number: 0
  entry_points:
    - meshio-convert = meshio._cli:convert
    - meshio-info = meshio._cli:info
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy
    - netCDF4
    - h5py

test:
  requires:
    - pytest
    - netCDF4
    - h5py
  source_files:
    - test
  imports:
    - meshio
  commands:
    - meshio-convert --help
    - meshio-info --help
    - cd test && python -m pytest

about:
  home: https://github.com/nschloe/meshio
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: I/O for various mesh formats

extra:
  recipe-maintainers:
    - nschloe
    - MuellerSeb
    - banesullivan
