{% set name = "meshio" %}
{% set version = "3.2.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 771afd7cbc695527dd9af44b6d38cc7a361fc145214e2aa9213716d4627ba445

build:
  noarch: python
  number: 0
  entry_points:
    - meshio-convert = meshio._cli:convert
    - meshio-info = meshio._cli:info
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - numpy
    - netCDF4
    - h5py
    - lxml

test:
  imports:
    - meshio
  commands:
    - meshio-convert --help
    - meshio-info --help

about:
  home: "https://github.com/nschloe/meshio"
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: "I/O for various mesh formats"

extra:
  recipe-maintainers:
    - nschloe
    - MuellerSeb
